### ISSUE TITLE
"q string" documentation malformed

### ISSUE THREAD

**Issue by bikezilla** [phrase/phrase-ruby#4]
Hi!

The "q string" documentation on https://github.com/phrase/phrase-ruby/blob/master/docs/KeysSearchParameters.md is malformed, trying to put an HTML table in a markdown document. 

I believe there are other markdown docs with the same issue. A grep search for "specify a query" should suffice them all.

**Comment by theSoenke** [comment]
Thanks @bikezilla for reporting this. We'll have a look to fix this

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-ruby) and we can take more direct action toward finding a solution.
